name: finalproject
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^3.3.4
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  intl: ^0.20.1
  path_provider: ^2.1.5
  flutter_downloader: ^1.11.8
  flutter_secure_storage: ^9.2.3
  bloc_test: ^9.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/
